### ISSUE TITLE
[NuGet tool installer] Certificate has expired

### ISSUE THREAD

**Issue by BrianMouncer** [microsoft/azure-pipelines-tool-lib#133] opened 2021-09-28 16:07 UTC
Duplicating this Issue here, since the other Issue does not seem to be getting much attention from the maintainers.
https://github.com/microsoft/azure-pipelines-tasks/issues/15316

Multiple teams have been hitting this random cert failure for the last week or two.
This seems to happen with both the V1 and V1 version of the pipeline task.

Please take a look and fix ASAP, thanks.

Starting: Use NuGet 4.9.4 
============================================================================== 
Task : NuGet tool installer 
Description : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this task to change the version of NuGet used in the NuGet tasks. 
Version : 0.179.1 
Author : Microsoft Corporation 
Help : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/prev-versions/nuget-installer-0 
============================================================================== 
ERR:certificate has expired 
Finishing: Use NuGet 4.9.4

**Comment by EzzhevNikita** [comment] 2022-03-22 10:58
@BrianMouncer NugetToolInstaller task itself doesn't use certificates, so we couldn't do much for this problem on our side. I think that could the problem on the server-side caused by an expired certificate on its side, also I don't see such an issue in my test pipeline runs. Do you still see this problem in your pipelines?

**Comment by anatolybolshakov** [comment] 2022-04-05 12:31
Hi @BrianMouncer do you have any updates?

**Comment by alexander-smolyakov** [comment] 2022-04-13 07:58
Hi @BrianMouncer, as it was mentioned earlier the NugetToolInstaller task doesn't use any certificates, so we couldn't do much to resolve this problem on our side with that being said let us close this ticket. Feel free to request a reopening if you have any further questions.

**Closed** 2022-04-14 12:43 UTC
